# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-01 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Картошка')),
                ('datetime', models.DateTimeField(default='20190101T01:01:01')),
                ('calories', models.IntegerField(default=0)),
            ],
        ),
    ]
