# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-01 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190301_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
